# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_auto_20171031_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='valid',
            field=models.CharField(default='valid', max_length=32),
        ),
    ]
